name: 'pnpm install'
description: 'Doing installs'
runs:
  using: 'composite'
  steps:
    - name: 'Setting up Node'
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - uses: pnpm/action-setup@v2
      with:
        version: 8

    - name: Install dependencies
      shell: bash
      run: pnpm install
